---
- name: Install Apache on Fedora-based systems
  hosts: all
  become: true
  tasks:
    - name: Install Apache (httpd)
      dnf:
        name: httpd
        state: present

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes



